### ISSUE TITLE
删我评论是吧，今晚别睡太死！

### ISSUE THREAD

**Issue by ASUKA-02** [JamyDon/PKU-SE-1#2]
😡😡😡

**Comment by JamyDon** [comment]
1

从 Windows 版邮件发送

发件人: ASUKA-02
发送时间: 2022年9月9日 10:36
收件人: JamyDon/PKU-SE-1
抄送: Subscribed
主题: [JamyDon/PKU-SE-1] 删我评论是吧，今晚别睡太死！ (Issue #2)

😡😡😡

**Comment by JamyDon** [comment]
1
