### ISSUE TITLE
还删还删，都第三次了还删！

### ISSUE THREAD

**Issue by ASUKA-02** [JamyDon/PKU-SE-1#3]
😡😡😡😡😡😡😡😡😡😤😤😤😤😤😤😤😤😤

**Comment by ASUKA-02** [comment]
> 😡😡😡😡😡😡😡😡😡😤😤😤😤😤😤😤😤😤

你是不是傻逼

**Comment by ASUKA-02** [comment]
> > 😡😡😡😡😡😡😡😡😡😤😤😤😤😤😤😤😤😤
> 
> 你是不是傻逼

什么人格分裂

**Comment by ASUKA-02** [comment]
> 

自己骂自己是吧？

**Comment by ASUKA-02** [comment]
> 
一眼烂活

**Comment by ASUKA-02** [comment]
> > > 😡😡😡😡😡😡😡😡😡😤😤😤😤😤😤😤😤😤
> > 
> > 
> > 你是不是傻逼
> 
> 什么人格分裂

话都让你说了大伙说什么？😅

**Comment by JamyDon** [comment]
6

**Comment by ASUKA-02** [comment]
> 6

1！
